### PR TITLE
Updates for v4.3.3

### PR DESCRIPTION
**Pull request by bmos**

### CODE REVIEW

**Comment by bmos** [comment]
Fixes #14

**Comment by bmos** [comment]
Also closes #15

**Comment by rushl** [comment]
I loaded up the test branch! It took me a while to spot the color. I think it would be better if the whole line changed color, so it stood out. Also, it would allow for notional containers which don't have a weight value to use the highlighting too. 

I updated my local with: 
```
local function onAnnounced(_, child)
	local sNodeName = DB.getName(child)
	for sNode, _ in pairs(tTooltips) do
		if sNodeName == sNode then
			-- Clear the control line.
			window.name.setLine(false, 0)
			window.location.setLine(false, 0)
			-- Set the font color.
			window.name.setColor(ColorManager.COLOR_HEALTH_CRIT_WOUNDS)
			window.location.setColor(ColorManager.COLOR_HEALTH_CRIT_WOUNDS)
			window.weight.setColor(ColorManager.COLOR_HEALTH_CRIT_WOUNDS)
			-- Replace the control line (now in the new color.)
			window.name.setLine(true, 0)
			window.location.setLine(true, 0)
			-- Add the tooltips.
			window.name.setTooltipText(string.format(Interface.getString('item_tooltip_overfull'), tTooltips[sNodeName]))
			window.location.setTooltipText(string.format(Interface.getString('item_tooltip_overfull'), tTooltips[sNodeName]))
			window.weight.setTooltipText(string.format(Interface.getString('item_tooltip_overfull'), tTooltips[sNodeName]))
			break
		end
	end
end

local function onUnannounced(source)
	local sNodeName = DB.getName(source)
	for sNode, _ in pairs(tTooltips) do
		if sNodeName == sNode then
			-- Clear the control line.
			window.name.setLine(false, 0)
			window.location.setLine(false, 0)
			-- Reset the font color to default.
			window.name.setColor(nil)
			window.location.setColor(nil)
			window.weight.setColor(nil)
			-- Replace the control line (now in the default color.)
			window.name.setLine(true, 0)
			window.location.setLine(true, 0)
			-- Remove the tooltips.
			window.name.setTooltipText('')
			window.location.setTooltipText('')
			window.weight.setTooltipText('')
			break
		end
	end
end
```

It looks great then, it really stands out!

Also, the item-count limits are amazing. It lets you do stuff like have a belt "container" that can hold 10 items, or perhaps make a "backpack exterior hooks" container with 5 items. So nice!

Finally, it looks like the weight boxes on the container have changed position. The Weight of item is first, the current weight is next, then the maximum weight, then the item counts. I don't know if that's intentional, but it stood out to me, since I had been used to the previous arrangement.

Thanks for your work!
Tim

**Comment by bmos** [comment]
Tim, unfortunately that would make it incompatible with https://github.com/FG-Unofficial-Developers-Guild/FG-CoreRPG-Inventory-Identified which is almost as popular as this one.

**Comment by bmos** [comment]
The change of the order of those fields was indeed intentional as this seemed more logical.
I'm open to discussion on that, as there is certainly an argument to be made against such changes.
Maybe adding field labels will help to avoid confusion for users?

**Comment by rushl** [comment]
> 

Hmm, I also have Inventory Identified, and I have had no trouble. What issue did you have?

**Comment by rushl** [comment]
> The change of the order of those fields was indeed intentional as this seemed more logical. I'm open to discussion on that, as there is certainly an argument to be made against such changes. Maybe adding field labels will help to avoid confusion for users?

I don't think the reorder is a big issue, as long as the user knows about it. I'd be concerned that labels would be too cluttered, especially if you're using two or three limits at once on a container. I'm using weight and count for most, and just count on a few.

**Comment by bmos** [comment]
The issue is that Inventory Identified sets the name red if it's not identified.
If this extension sets the name as red for different reasons, it can be unclear why it's red.
I've compensated for this by making the name and location only turn red if you aren't using the other extension, while the weight is always red.
I think I have found a better solution:
image

**Comment by bmos** [comment]
and here is what those field labels look like.
image

**Comment by rushl** [comment]
> The issue is that Inventory Identified sets the name red if it's not identified. If this extension sets the name as red for different reasons, it can be unclear why it's red. I've compensated for this by making the name and location only turn red if you aren't using the other extension, while the weight is always red. I think I have found a better solution

Oh, the weight field color change is nice! Can you confirm that it still changes color even if the weight of the container is 0 or blank?

**Comment by bmos** [comment]
it does!
thanks for suggesting that though. important to have tested it.

**Comment by rushl** [comment]
> it does! thanks for suggesting that though. important to have tested it.

It seems like the item-count restriction only applies to Carried items. Equipped items don't count (but I think they should), and Not-Carried items don't count (which is correct).

**Comment by rushl** [comment]
Oh, also, we see the current weight. Could we also see the current item count? Once you get 15 or 20 items with different counts (3 of these, 7 of those, etc.) it gets difficult to see how many over you are. Also, the item count seems to be working well for nested containers (the items in the sub-container don't count against the main container), however it's difficult to sort out the total number of items in the main container. So having the current item count visible would help there too.

Thanks!

**Comment by bmos** [comment]
> Equipped items don't count (but I think they should)

How can you have something equipped if it's in a bag?

**Comment by rushl** [comment]
> > Equipped items don't count (but I think they should)
> 
> How can you have something equipped if it's in a bag?

Hmm, I've been using the item count to keep track of slots, and that's useful to know in either Equipped state. But I think I'm starting to see it the same way as you - Equipped items shouldn't count against weight or item count.

**Comment by bmos** [comment]
How important is seeing the weight, volume, and count of contents when they haven't gone over the max? Like does it just matter to know how far in excess you are or do you want to know when you're half full and such?
I have added the current and limit to the tooltip but it is only there when it is exceeded
image

**Comment by bmos** [comment]
The reason I am hesitant to just add a field for it is that the sheet already gets so many when you enable volume. I'm not sure how many users actually use volume.

**Comment by rushl** [comment]
Adding the current counts to a tooltip seems like a much better idea than having it on the container item itself. Not only does it save space on the container item entry, but it makes it accessible without having to even open the item. I'd suggest:

- Have the tool tip list the current weight/count/volume. 
- Make the current text red if it's over the limit, plus keep the red field like you have now.
- On the item's entry, just have the boxes to set the maximum values. Perhaps make them red if that value is exceeded.

So from the inventory screen, you can quickly see which containers have exceeded a condition, and via the tooltip, which condition (since that condition's current value text will be red). You only need to open the container's entry itself if you need to change the maximum values.

(Note, if you can't make tooltip text red, you can append/prepend a * next to the value to indicate it exceeds the maximum.)

**Comment by bmos** [comment]
1. Current weight is there in the image I posted.
2. Tooltip text can't be formatted.
3. Is it ok that there would be no way to see current values until they exceed the maximum? That seems like the sort of thing users would want.
Here's a UI redesign I made that _does_ add those fields (and keeps the tooltip shown previously).
image

**Comment by rushl** [comment]
I'm testing this branch, and I'm getting an error when I have contents counts turned on, but volume counts turned off. It's saying the capacityweight control is anchoring to an uncalculated control (extraplanarcontents) in the item_main windowclass.

**Comment by bmos** [comment]
Which ruleset?

**Comment by bmos** [comment]
> I'm testing this branch, and I'm getting an error when I have contents counts turned on, but volume counts turned off.

Thanks for reporting that. Took me a while to find it but Zarestia helped point me in the right direction.

**Comment by bmos** [comment]
Fixes #13 although it can be jarring when items disappear

**Pull request merged**
