### PR TITLE
item record changes for PFRPG2 support

### PR DESCRIPTION
**Pull request by BurcinSayin**
On PFRPG2 there is no weight. That row hidden field on item record on PF2 ruleset. Instead "Bulk" is used. In effect you can not see or edit fields like "Maximum Weight Capacity" or "Weight of Contents" in PF2 item details 

Aside from item details screen all other calculations seems to be working ok. Fixes here are just adding a new row for these container properties just above the "Bulk" row.

Before fix:
image

After fix
image

### CODE REVIEW

**Review by bmos — APPROVED** [review]

**Comment by bmos** [comment]
Awesome! Thanks for this!
Can you do a final test before release?
The main branch should be ready.
I don't know PFRPG2's ruleset in FG well so I am not confident I'll find any issues.

**Comment by bmos** [comment]
Also, would it make sense to use the "extradimensional" trait to detect bags of holding as such? Or is that used for things that aren't containers?

**Comment by BurcinSayin** [comment]
> Also, would it make sense to use the "extradimensional" trait to detect bags of holding as such? Or is that used for things that aren't containers?

All extradimentional container items do have that trait. But there are other items with same trait which are not containers. So I think checking from name is a "safer"  approach.

I also tested the main branch on my test and actual PF2 campaigns it seems to be working  just fine.

**Comment by bmos** [comment]
> > Also, would it make sense to use the "extradimensional" trait to detect bags of holding as such? Or is that used for things that aren't containers?
> 
> All extradimentional container items do have that trait. But there are other items with same trait which are not containers. So I think checking from name is a "safer" approach.

Ah, that is what I was worried about. Thanks for clarifying that.

> I also tested the main branch on my test and actual PF2 campaigns it seems to be working just fine.

Awesome! It has been released!

**Pull request merged**
